### ISSUE TITLE
넥슨 중간발표 이후 스토리 개선

### ISSUE THREAD

**Issue by majecty** [SNUGDC/Deathwish#3]
@Zannetic  @renios  @JYPark1101 

내용은 여기에 쓰레드 달아서 처리해주세요.

**Comment by Zannetic** [comment]
스토리측면에서 작업해야하는 것은 크게 4가지입니다:

1) 배경스토리 정리
	얘가 어떤 과거가 있고, 아픔이 있고, 슬픔이 있는지 (트라우마)
	중환자실에 오게 된 이유: 우울증? 자해? 자살?
                     >  @JeongMunKyu  @zannetic이 딥다크스토리 작업
                     >  @JYPark1101 보조

2) 스테이지 진행에 따라 발전하는 그림자와의 관계정리
	그림자를 처음 만남 > 경계함 > 친해짐 > 의지함 > 병적으로 의존함
	어느 스테이지에서 어느 정도로 진전된 관계를 보여주는지
                    >  @JYPark1101 작업

3) 인게임 텍스트
	어느 지점에서 어떤 텍스트가 뜰지
	빛 버전 / 그림자 버전 별도 텍스트
	위에서 정리한 배경스토리와 그림자와의 관계에 기반하여 작성

4) 다른 형식의 텍스트 등장
	현재 텍스트는 게임 진행중에 캐릭터가 멈추고 진행키를 눌러야 텍스트가 넘어가짐
	진행키를 누르지 않아도 특정 장소를 지날 때 자동으로 뜨고 사라지는 텍스트를 추가하려합니다.
	데스/위시의 대화가 아닌 다른 텍스트 (수근거림, 환청 등) 표현
                    >  프밍팀 별도요청

* 1번, 2번사항을 작업하여 화요일 저녁에 공유하기로 하였습니다*
* 민정언니 스토리텍스트 참고할 것*

**Comment by JeongMunKyu** [comment]
그녀의 과거
그녀는 지극히 평범한 가정에서 태어났다. 평범하게 예쁘고, 평범하게 잔병치레도 했으며, 평범하게 친구들도 사귀었다.
하지만 그랬기에 이후의 불행한 일들이 더더욱 그녀를 벼랑끝으로 몰아갔는지도 모른다.
그녀가 막 10살이 됬을때, 그녀의 아버지가 교통사고로 죽었다. 
다음날부터 검은 양복을 입은 우락부락한 괴한들이 집에 찾아오기 시작했다.
처음에는 그녀의 어머니와 대화를 하는 정도였다. 
그녀는 처음보는 괴한들에게 고개를 들지 못하고 굽실대는 어머니를 이해할 수 없었다.
한달이 지나고, 두달이 지나자 괴한들은 어느순간 돌변했다.
괴한이 찾아오면 그녀의 어머니는 그녀가 보는 앞에서 무자비하게 얻어맞았다. 
아침에 그녀가 눈뜨기 전에 나가서 밤 늦게 들어오던 어머니가 맞은 다음날에는 하루종일 움직이지 못했다.
이런 일이 몇번이나 반복되자 그녀의 어머니는 그녀를 어떤 아줌마에게 대려갔다. 
그녀의 어머니는 그 사람을 이모라고 부르라고 했다. 그녀는 일이 많아서 챙겨줄 수가 없으니 그곳에 몇일만 있으라고 했다. 
낯선 잠자리에서 잠을 설친 그녀는 잠결에 누군가의 신경질적인 목소리를 들었다.
그리고 몇일 후, 그녀의 어머니가 죽었다.
친구들의 태도가 돌변했다. 
처음에는 걱정해주고 위로해주던 친구들이 그녀를 모른체하기 시작했고, 몇몇은 그녀를 괴롭히기 시작했다. 
화를 참지 못하고 싸우고 나면 선생님은 소녀를 때렸다. 
부모님께서 돌아가시면 어른스럽게 대처해야 하는데 그러지 않았기 때문이라고 했다.
그녀는 더 이상 괴롭힘에 대항할 수가 없었다. 그러자 괴롭힘은 더욱 심해졌다. 
아이들은 수업중에 그녀에게 종이비행기를 던지기도 했고, 물통에 물을 담아 그녀에게 뿌리기도 했다. 
심할 때에는 그녀의 물건을 망가뜨리거나 옷을 찢어버리기도 했다. 
그런날에는 이모에게 온몸에 멍이 들도록 맞아야 했다. 
 
그리고 어느날
그날은 유난스럽게 괴롭힘이 심했다. 그녀는 아이들에게 붙들린 채로 얼굴에 낙서를 당하고 있었다. 한 아이가 들고있던 펜이 눈을 찔렀다. 그녀는 참지못하고 몸부림쳤다. 순간 그녀가 휘두른 손이 옆에 있던 아이의 눈을 찔렀다. 그리고 무슨일이 있었는지는 기억나지 않았다. 소란이 잦아들고 그녀가 정신을 차리고 나니 그녀는 어른들 앞에 무릎꿇려 있었다. 어른들은 그녀를 무서운 눈으로 노려보고 있었고, 한 여자는 그녀에게 고래고래 소리를 질렀다. 
이해할 수 없었다.
우리 애 눈에 무슨일이라도 생기면 어떻게 할거야! 이 부모도 없는 년아!
무서웠다
쯧쯧… 아무리 화가나도 어떻게 이런짓을….
억울했다
죽어버려!
아
그런 방법이 있었구나

**Comment by renios** [comment]
잘 읽어보았습니다. 다들 어째 어둠의 다크한 스토리를 쓰는데 꽤나 능숙...
다만 지금 스토리가 상당히 구체적인데, 
이것들을 전부 설명할 수는 없기 때문에 (일일이 설명하면 오히려 분위기가 깨지겠죠)
일단 상징화나 비유를 통해 추려야 할 것 같습니다.

마지막 부분을 약간 추가해보자면
어른들의 화내는 것을 듣고 바로 죽고싶다는 생각을 한 것이 아니라, 
그렇게 절망적인 상황에서 집에 돌아오던 중 
길을 건너다 차에 치일 뻔 하는 상황에서 다행스럽게도 차가 바로 앞에서 멈췄지만 
위시가 그 순간 '멈춰서 다행이다' 가 아니라, '멈추지 않고 그대로 치였으면 내일이 오지 않아도 됐을 텐데...' 
라는 생각을 했고 그 이후로 죽음을 유일한 탈출구로 인식하면서 삶의 의미를 잃어간다는 이야기는 어떨까요?

절망적인 삶을 개선(?) 하는 방법은 삶 그 자체가 나아지는 방향도 있지만, 
역으로 더이상 살지 않는다면 절망적이지도 않겠지요. (물론 이것은 제 개인적인 견해일 뿐입니다)

+ 펜에서 영감을 얻은 부분인데, 어떤 이벤트 이전 / 이후 에서는 빛 상태의 가시가 마치 날카로운 펜처럼 보이는 연출은 어떨까요?

+ 위시가 트라우마를 가지게 된 대상 중 '물'이 포함된다면, 챕터 2에서 자유롭게 물 속을 이동하는 것에 대해 연관된 설정? 설명?이 있었으면 합니다. (실제로 게임상 과거의 기억 / 현재의 두려움 극복 등이 제시되지 않더라도 일단 설정 정도는...?)

**Comment by JeongMunKyu** [comment]
코멘트 감사합니다
-물론 우리 게임에 설명충을 넣을 순 없으니 이후 작업에 중요부분을 컷씬으로 대체하거나 플레이어가 적당히 짐작할만한 대사로 대체해야죠ㅎㅎ
-마지막부분은 나중에 친구들, 어른들이 유령으로 나타난 위시를 보고 놀라는 장면에 적합하려면 죽으라는 말을 듣는쪽이 더 진행하기 편해 보입니다.
-가시의 모양은 처음 기획에 풀과 비슷해 보이도록 기획했었기 때문에 잘 모르겠네요
-확실히 물에 트라우마가 있으면 수영을 자유롭게 하는 것은 이상하겠네요
‘원래 수영을 굉장히 잘했는데 친구들이 그걸 보고 질투하고 위시가 화장실에 있을 때 물을 부었다. 그런데 한번은 물과함께 양동이도 떨어져 상처를 입었다’는 건 어떨까요?
그래서 떨어지는 물은 데미지를 입는걸로….(물맵 보스맵을 의도한 짜맞추기….)
