### ISSUE TITLE
넥슨 버전에 빠진 사운드 이펙트 넣기

### ISSUE THREAD

**Issue by majecty** [SNUGDC/Deathwish#4]
@JYPark1101 @JeongMunKyu  넥슨 발표 버전에서 나오지 않는 사운드 이펙트 정리해주세요.

**Comment by JeongMunKyu** [comment]
사운드 이펙트 미적용 부분

1.	UI사운드 이펙트
2.	번개맵 딜레이에(번개와 번개 사이에) 비소리 안남
3.	거울
4.	물속 들어갈 때, 헤엄칠 때
5.	무너지는 바닥
6.	바람
