### ISSUE TITLE
카메라 이동 기능

### ISSUE THREAD

**Issue by renios** [SNUGDC/Deathwish#7]
맵을 둘러보기 위한 카메라 이동 기능을 구현하려고 합니다.
1. 화살표 위아래 키 사용
   - 별도의 키를 추가하지 않고도 유저가 사용 가능.
   - 위 / 아래만 둘러볼 수 있음.
   - 사다리, 거울과 같이 위/아래 키로 조작해야 하는 상황에서는 사용 불가능
2. 별도의 버튼 + 화살표키로 사용 (예: shift + 방향키)
   - 4방향 모두를 언제나 둘러볼 수 있음.
   - 별도의 키가 하나 더 필요함.

어떤 방법이 좋을까요? 기획자분들 의견 주세요.

**Comment by majecty** [comment]
저는 다음 특징들을 가지면 좋다고 생각합니다.
  * 화살표 위아래 키 사용
  * 사다리, 거울에서 사용 불가
  * 가능하다면 벽에 도달해서 더 갈 수 없는 상황에서 가로로 카메라 이동도 가능

그 이유는 추가 버튼이 생기면 게임 조작이 많이 복잡해질 것 같다고 생각해서에요. 우리가 플랫포머 게임 매니아들 대상이라기 보다 게임을 많이 안해본 유저들도 쉽게 스토리 보면서 할 수 있으면 좋겠다고 생각해서에요.

**Comment by Zannetic** [comment]
저도 1번방법이 좋다고 생각합니다. 
조작은 항상 간단했으면합니다.

그리고 문규씨가 스크롤링기능이 생김에 따라 게임의 난이도가 많이 낮아지지않을까 걱정했는데,
맵의 끝과 끝을 보게해주는 스크롤링보다는 제한적인 스크롤링이 좋지 않을까 제안해봅니다.

**Comment by renios** [comment]
�������� �� ���� �������� ������ ������ ����������.
��/���� ���������� �� ������ ����/������ ���������� �� �� �������� �� �� ��������.

���� ���� ���� ���������� ���� ������ �� ���� ���� �������� ������ ������ ���� ������ �������� �������� �������� ������ �� ������ ������ ������������.

**Comment by renios** [comment]
답장으로 온 의견 기준으로 첫번째 기능을 넣었습니다.
위/아래 스크롤링은 잘 되는데 왼쪽/오른쪽 스크롤링을 좀 더 다듬어야 할 것 같습니다.

거울 효과 도중 스크롤링이 되면 카메라 두 개가 서로 어긋나는 문제가 있어서 거울 효과가 보여지는 도중에는 캐릭터를 조작할 수 없도록 기능을 추가했습니다.

** 깃헙 이슈에 메일로 답장을 보내면 여기에도 올라가는데, 맥에서 보내면 한글이 깨져 보이네요...
방금 받은 정체불명의 메일은 사실 이 내용입니다 ㅜㅜ
