### ISSUE TITLE
보스맵 제안

### ISSUE THREAD

**Issue by JeongMunKyu** [SNUGDC/Deathwish#8]
보스맵에 대하여 기획을 해보았습니다
일단 기획에 앞서서 필요한 새로운 설정은

"그림자에서도 일부 오브젝트들은 움직이기도 한다"

이 오브젝트들은 위시에게 있었던 무섭고 고통스럽고 슬펐던 기억으로 그 기억들이 형상화 되어나타나고 위시에게 그것들은 움직여서 자신에게 고통을 주는 것들이므로 위시에게 고통을 주는 방향으로 '움직입니다'

설정을 이렇게 한다면?
1. 비행기
   -왕따였던 위시에게 친구들이 괴롭히면서 비행기를 날려 맞추었던 나쁜 기억
2. 떨어지는 물, 높아지는 수위
   -수영장에서 아이들이 수영을 하지 못하는 위시를 수영장으로 밀어넣어 물에 빠졌던 기억
3. 쫓아오는 괴물(사실은 돌덩어리가 쌓인 그림자)
   -부모님이 돌아가시고 자신을 맡아서 기르기로 한 ???가 위시를 학대하던 때의 기억

감사합니다
++아이디어 모집중!

**Comment by majecty** [comment]
그러면 보스전은 오리나 super meat boy처럼 거대한 적이 오는 걸 피하는 식이 되는 건가요?
자신이 슬퍼했던 기억들이 적으로 나오는 컨셉 좋네요.

궁금한 게 있는데 굳이 "그림자에서도 일부 오브젝트들이 움직이기도 한다" 설정이 왜 필요한 지 잘 모르겠어요. 빛일 때도 나타나서 위시에게 고통을 줄 수 있는데 움직이는 그림자로 했을 때 뭐가 더 좋아지는 지 잘 모르겠어요.

**Comment by Zannetic** [comment]
'쫓아오는 괴물 = 사실은 돌덩이 그림자' 같은 설정을 위해 그림자모드가 필요한건가요?
그림자모드에서는 움직이는 것이 없다는 컨셉을 유지했으면합니다.

빛모드에서도 실루엣 형태를 유지한다는 설정은 어떤가요?
ex) 그림자모드에서도 빛모드에서도 실루엣형태, 대신 움직이는것은 빛모드에서만
그리고 트라우마를 안은건 "위시"이므로 빛 모드에서 보스가 쫓아오는게 더 맞을 듯 합니다

**Comment by renios** [comment]
저는 오히려 그림자 괴물(?)이 움직일 수도 있다고 생각했습니다. 데스가 그림자 세계에서 위시처럼 자유롭게 움직이듯이 그림자 괴물도 뭔가 특수한 존재라는 느낌이었는데요.
빛모드에서도 실루엣이라는 접근이 새로웠습니다. 종종 미디어에서 과거의 트라우마를 형체불명의 괴물로 묘사하는데 비슷한 느낌일까요? 
그림자에서 앞을 가로막은 거대한 물체를 봄 -> (통과할 다른 방도가 없다고 느낀 유저가) 빛으로 전환 -> 그러나 어두운 실루엣 그대로인 거대한 물체 -> 위시를 공격&추격하기 시작
이런 스토리는 어떨까요?
